
var loadYoga = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
    function (loadYoga = {}) {

      function aa() { g.buffer != q.buffer && r(); return q } function w() { g.buffer != q.buffer && r(); return ba } function ca() { g.buffer != q.buffer && r(); return da } function ea() { g.buffer != q.buffer && r(); return fa } function x() { g.buffer != q.buffer && r(); return ha } function y() { g.buffer != q.buffer && r(); return ia } function ja() { g.buffer != q.buffer && r(); return la } var A; A || (A = typeof loadYoga !== 'undefined' ? loadYoga : {}); var ma, na; A.ready = new Promise((a, b) => { ma = a; na = b });
      var oa = Object.assign({}, A), pa = (a, b) => { throw b; }, qa = "object" == typeof window, C = "function" == typeof importScripts, D = "object" == typeof process && "object" == typeof process.versions && "string" == typeof process.versions.node, E = A.ENVIRONMENT_IS_PTHREAD || !1, F = ""; function ra(a) { return A.locateFile ? A.locateFile(a, F) : F + a } var sa, ta;
      if (D) {
        var fs = require("fs"), ua = require("path"); F = C ? ua.dirname(F) + "/" : __dirname + "/"; sa = (b, c) => { b = b.startsWith("file://") ? new URL(b) : ua.normalize(b); return fs.readFileSync(b, c ? void 0 : "utf8") }; ta = b => { b = sa(b, !0); b.buffer || (b = new Uint8Array(b)); return b }; process.argv.slice(2); pa = (b, c) => { process.exitCode = b; throw c; }; A.inspect = () => "[Emscripten Module object]"; let a; try { a = require("worker_threads") } catch (b) {
          throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),
          b;
        } global.Worker = a.Worker
      } else if (qa || C) C ? F = self.location.href : "undefined" != typeof document && document.currentScript && (F = document.currentScript.src), _scriptDir && (F = _scriptDir), 0 !== F.indexOf("blob:") ? F = F.substr(0, F.replace(/[?#].*/, "").lastIndexOf("/") + 1) : F = "", D || (sa = a => { var b = new XMLHttpRequest; b.open("GET", a, !1); b.send(null); return b.responseText }, C && (ta = a => { var b = new XMLHttpRequest; b.open("GET", a, !1); b.responseType = "arraybuffer"; b.send(null); return new Uint8Array(b.response) }));
      D && "undefined" == typeof performance && (global.performance = require("perf_hooks").performance); var va = console.log.bind(console), wa = console.error.bind(console); D && (va = (...a) => fs.writeSync(1, a.join(" ") + "\n"), wa = (...a) => fs.writeSync(2, a.join(" ") + "\n")); var xa = A.print || va, G = A.printErr || wa; Object.assign(A, oa); oa = null; A.quit && (pa = A.quit); var ya; A.wasmBinary && (ya = A.wasmBinary); var noExitRuntime = A.noExitRuntime || !0; "object" != typeof WebAssembly && I("no native wasm support detected");
      var g, za, Aa = !1, J, q, ba, da, fa, ha, ia, Ba, la; function r() { var a = g.buffer; A.HEAP8 = q = new Int8Array(a); A.HEAP16 = da = new Int16Array(a); A.HEAP32 = ha = new Int32Array(a); A.HEAPU8 = ba = new Uint8Array(a); A.HEAPU16 = fa = new Uint16Array(a); A.HEAPU32 = ia = new Uint32Array(a); A.HEAPF32 = Ba = new Float32Array(a); A.HEAPF64 = la = new Float64Array(a) } var Ca = A.INITIAL_MEMORY || 16777216; 65536 <= Ca || I("INITIAL_MEMORY should be larger than STACK_SIZE, was " + Ca + "! (STACK_SIZE=65536)");
      if (E) g = A.wasmMemory; else if (A.wasmMemory) g = A.wasmMemory; else if (g = new WebAssembly.Memory({ initial: Ca / 65536, maximum: 32768, shared: !0 }), !(g.buffer instanceof SharedArrayBuffer)) throw G("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"), D && G("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
        Error("bad memory"); r(); Ca = g.buffer.byteLength; var Da, Ea = [], Fa = [], Ga = [], Ha = 0; function Ia() { return noExitRuntime || 0 < Ha } function Ja() { var a = A.preRun.shift(); Ea.unshift(a) } var K = 0, Ka = null, La = null; function I(a) { if (A.onAbort) A.onAbort(a); a = "Aborted(" + a + ")"; G(a); Aa = !0; J = 1; a = new WebAssembly.RuntimeError(a + ". Build with -sASSERTIONS for more info."); na(a); throw a; } function Ma(a) { return a.startsWith("data:application/octet-stream;base64,") } var L; L = "wasm-async.wasm"; Ma(L) || (L = ra(L));
      function Na(a) { try { if (a == L && ya) return new Uint8Array(ya); if (ta) return ta(a); throw "both async and sync fetching of the wasm failed"; } catch (b) { I(b) } } function Oa(a) { return ya || !qa && !C || "function" != typeof fetch ? Promise.resolve().then(() => Na(a)) : fetch(a, { credentials: "same-origin" }).then(b => { if (!b.ok) throw "failed to load wasm binary file at '" + a + "'"; return b.arrayBuffer() }).catch(() => Na(a)) }
      function Pa(a, b, c) { return Oa(a).then(d => WebAssembly.instantiate(d, b)).then(d => d).then(c, d => { G("failed to asynchronously prepare wasm: " + d); I(d) }) } function Qa(a, b) { var c = L; return ya || "function" != typeof WebAssembly.instantiateStreaming || Ma(c) || D || "function" != typeof fetch ? Pa(c, a, b) : fetch(c, { credentials: "same-origin" }).then(d => WebAssembly.instantiateStreaming(d, a).then(b, function (f) { G("wasm streaming compile failed: " + f); G("falling back to ArrayBuffer instantiation"); return Pa(c, a, b) })) }
      function Ra(a) { this.name = "ExitStatus"; this.message = "Program terminated with exit(" + a + ")"; this.status = a } function Sa(a) { a.terminate(); a.onmessage = () => { } } function Ta(a) { (a = M.na[a]) || I(); M.lb(a) }
      function Ua(a, b, c) { c = b + c; for (var d = ""; !(b >= c);) { var f = a[b++]; if (!f) break; if (f & 128) { var e = a[b++] & 63; if (192 == (f & 224)) d += String.fromCharCode((f & 31) << 6 | e); else { var k = a[b++] & 63; f = 224 == (f & 240) ? (f & 15) << 12 | e << 6 | k : (f & 7) << 18 | e << 12 | k << 6 | a[b++] & 63; 65536 > f ? d += String.fromCharCode(f) : (f -= 65536, d += String.fromCharCode(55296 | f >> 10, 56320 | f & 1023)) } } else d += String.fromCharCode(f) } return d } function Va(a) { if (E) return Wa(1, 1, a); J = a; if (!Ia()) { M.qb(); if (A.onExit) A.onExit(a); Aa = !0 } pa(a, new Ra(a)) }
      function Xa(a) { J = a; if (E) throw Ya(a), "unwind"; Va(a) } function Za(a) { a instanceof Ra || "unwind" == a || pa(1, a) }
      var M = {
        ua: [], ta: [], Na: [], na: {}, cb: function () { E && M.eb() }, tb: function () { }, eb: function () { M.receiveObjectTransfer = M.kb; M.threadInitTLS = M.Ma; M.setExitStatus = M.La; noExitRuntime = !1 }, La: function (a) { J = a }, wb: ["$terminateWorker"], qb: function () { for (var a of M.ta) Sa(a); for (a of M.ua) Sa(a); M.ua = []; M.ta = []; M.na = [] }, lb: function (a) { var b = a.ra; delete M.na[b]; M.ua.push(a); M.ta.splice(M.ta.indexOf(a), 1); a.ra = 0; $a(b) }, kb: function () { }, Ma: function () { M.Na.forEach(a => a()) }, hb: a => new Promise(b => {
          a.onmessage = e => {
            e = e.data; var k =
              e.cmd; a.ra && (M.Qa = a.ra); if (e.targetThread && e.targetThread != ab()) { var h = M.na[e.vb]; h ? h.postMessage(e, e.transferList) : G('Internal error! Worker sent a message "' + k + '" to target pthread ' + e.targetThread + ", but that thread no longer exists!") } else if ("checkMailbox" === k) bb(); else if ("spawnThread" === k) { if (k = M.Va()) M.ta.push(k), M.na[e.ra] = k, k.ra = e.ra, h = { cmd: "run", start_routine: e.ub, arg: e.sb, pthread_ptr: e.ra }, D && k.unref(), k.postMessage(h, e.xb) } else if ("cleanupThread" === k) Ta(e.thread); else if ("killThread" ===
                k) e = e.thread, k = M.na[e], delete M.na[e], Sa(k), $a(e), M.ta.splice(M.ta.indexOf(k), 1), k.ra = 0; else if ("cancelThread" === k) M.na[e.thread].postMessage({ cmd: "cancel" }); else if ("loaded" === k) a.loaded = !0, b(a); else if ("print" === k) xa("Thread " + e.threadId + ": " + e.text); else if ("printErr" === k) G("Thread " + e.threadId + ": " + e.text); else if ("alert" === k) alert("Thread " + e.threadId + ": " + e.text); else if ("setimmediate" === e.target) a.postMessage(e); else if ("callHandler" === k) A[e.handler](...e.args); else k && G("worker sent an unknown command " +
                  k); M.Qa = void 0
          }; a.onerror = e => { G("worker sent an error! " + e.filename + ":" + e.lineno + ": " + e.message); throw e; }; D && (a.on("message", function (e) { a.onmessage({ data: e }) }), a.on("error", function (e) { a.onerror(e) })); var c = [], d = ["onExit", "onAbort", "print", "printErr"], f; for (f of d) A.hasOwnProperty(f) && c.push(f); a.postMessage({ cmd: "load", handlers: c, urlOrBlob: A.mainScriptUrlOrBlob || _scriptDir, wasmMemory: g, wasmModule: za })
        }), gb: function (a) { a() }, Oa: function () { var a = ra("wasm-async.worker.js"); a = new Worker(a); M.ua.push(a) },
        Va: function () { 0 == M.ua.length && (M.Oa(), M.hb(M.ua[0])); return M.ua.pop() }
      }; A.PThread = M; function cb(a) { for (; 0 < a.length;)a.shift()(A) } A.establishStackSpace = function () { var a = ab(), b = x()[a + 52 >> 2]; a = x()[a + 56 >> 2]; db(b, b - a); eb(b) }; function Ya(a) { if (E) return Wa(2, 0, a); Xa(a) } A.invokeEntryPoint = function (a, b) { a = Da.get(a)(b); Ia() ? M.La(a) : fb(a) }; function gb(a) { if (void 0 === a) return "_unknown"; a = a.replace(/[^a-zA-Z0-9_]/g, "$"); var b = a.charCodeAt(0); return 48 <= b && 57 >= b ? `_${a}` : a }
      function hb(a, b) { a = gb(a); return { [a]: function () { return b.apply(this, arguments) } }[a] } var N = new function () { this.oa = [void 0]; this.Fa = []; this.get = function (a) { return this.oa[a] }; this.has = function (a) { return void 0 !== this.oa[a] }; this.$a = function (a) { var b = this.Fa.pop() || this.oa.length; this.oa[b] = a; return b }; this.ab = function (a) { this.oa[a] = void 0; this.Fa.push(a) } };
      function ib(a) { var b = Error, c = hb(a, function (d) { this.name = a; this.message = d; d = Error(d).stack; void 0 !== d && (this.stack = this.toString() + "\n" + d.replace(/^Error(:[^\n]*)?\n/, "")) }); c.prototype = Object.create(b.prototype); c.prototype.constructor = c; c.prototype.toString = function () { return void 0 === this.message ? this.name : `${this.name}: ${this.message}` }; return c } var O = void 0; function P(a) { throw new O(a); }
      var jb = a => { a || P("Cannot use deleted val. handle = " + a); return N.get(a).value }, kb = a => { switch (a) { case void 0: return 1; case null: return 2; case !0: return 3; case !1: return 4; default: return N.$a({ Ka: 1, value: a }) } }, lb = void 0, mb = void 0; function Q(a) { for (var b = ""; w()[a];)b += mb[w()[a++]]; return b } var nb = []; function ob() { for (; nb.length;) { var a = nb.pop(); a.ea.wa = !1; a["delete"]() } } var pb = void 0, R = {}; function qb(a, b) { for (void 0 === b && P("ptr should not be undefined"); a.ia;)b = a.ya(b), a = a.ia; return b } var S = {};
      function rb(a) { a = sb(a); var b = Q(a); T(a); return b } function tb(a, b) { var c = S[a]; void 0 === c && P(b + " has unknown type " + rb(a)); return c } function ub() { } var vb = !1; function wb(a) { --a.count.value; 0 === a.count.value && (a.ka ? a.la.pa(a.ka) : a.ha.fa.pa(a.ga)) } function xb(a, b, c) { if (b === c) return a; if (void 0 === c.ia) return null; a = xb(a, b, c.ia); return null === a ? null : c.Sa(a) } var yb = {}; function zb(a, b) { b = qb(a, b); return R[b] } var Ab = void 0; function Bb(a) { throw new Ab(a); }
      function Cb(a, b) { b.ha && b.ga || Bb("makeClassHandle requires ptr and ptrType"); !!b.la !== !!b.ka && Bb("Both smartPtrType and smartPtr must be specified"); b.count = { value: 1 }; return U(Object.create(a, { ea: { value: b } })) } function U(a) { if ("undefined" === typeof FinalizationRegistry) return U = b => b, a; vb = new FinalizationRegistry(b => { wb(b.ea) }); U = b => { var c = b.ea; c.ka && vb.register(b, { ea: c }, b); return b }; ub = b => { vb.unregister(b) }; return U(a) } var Db = {}; function Eb(a) { for (; a.length;) { var b = a.pop(); a.pop()(b) } }
      function Fb(a) { return this.fromWireType(x()[a >> 2]) } var Gb = {}, Hb = {}; function V(a, b, c) { function d(h) { h = c(h); h.length !== a.length && Bb("Mismatched type converter count"); for (var l = 0; l < a.length; ++l)W(a[l], h[l]) } a.forEach(function (h) { Hb[h] = b }); var f = Array(b.length), e = [], k = 0; b.forEach((h, l) => { S.hasOwnProperty(h) ? f[l] = S[h] : (e.push(h), Gb.hasOwnProperty(h) || (Gb[h] = []), Gb[h].push(() => { f[l] = S[h]; ++k; k === e.length && d(f) })) }); 0 === e.length && d(f) }
      function Ib(a) { switch (a) { case 1: return 0; case 2: return 1; case 4: return 2; case 8: return 3; default: throw new TypeError(`Unknown type size: ${a}`); } }
      function W(a, b, c = {}) { if (!("argPackAdvance" in b)) throw new TypeError("registerType registeredInstance requires argPackAdvance"); var d = b.name; a || P(`type "${d}" must have a positive integer typeid pointer`); if (S.hasOwnProperty(a)) { if (c.bb) return; P(`Cannot register type '${d}' twice`) } S[a] = b; delete Hb[a]; Gb.hasOwnProperty(a) && (b = Gb[a], delete Gb[a], b.forEach(f => f())) } function Jb(a) { P(a.ea.ha.fa.name + " instance already deleted") } function X() { }
      function Kb(a, b, c) { if (void 0 === a[b].ja) { var d = a[b]; a[b] = function () { a[b].ja.hasOwnProperty(arguments.length) || P(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].ja})!`); return a[b].ja[arguments.length].apply(this, arguments) }; a[b].ja = []; a[b].ja[d.va] = d } }
      function Lb(a, b) { A.hasOwnProperty(a) ? (P(`Cannot register public name '${a}' twice`), Kb(A, a, a), A.hasOwnProperty(void 0) && P("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"), A[a].ja[void 0] = b) : A[a] = b } function Mb(a, b, c, d, f, e, k, h) { this.name = a; this.constructor = b; this.qa = c; this.pa = d; this.ia = f; this.Ua = e; this.ya = k; this.Sa = h; this.Ia = [] }
      function Nb(a, b, c) { for (; b !== c;)b.ya || P(`Expected null or instance of ${c.name}, got an instance of ${b.name}`), a = b.ya(a), b = b.ia; return a } function Ob(a, b) { if (null === b) return this.Ca && P(`null is not a valid ${this.name}`), 0; b.ea || P(`Cannot pass "${Pb(b)}" as a ${this.name}`); b.ea.ga || P(`Cannot pass deleted object as a pointer of type ${this.name}`); return Nb(b.ea.ga, b.ea.ha.fa, this.fa) }
      function Qb(a, b) {
        if (null === b) { this.Ca && P(`null is not a valid ${this.name}`); if (this.Ba) { var c = this.Da(); null !== a && a.push(this.pa, c); return c } return 0 } b.ea || P(`Cannot pass "${Pb(b)}" as a ${this.name}`); b.ea.ga || P(`Cannot pass deleted object as a pointer of type ${this.name}`); !this.Aa && b.ea.ha.Aa && P(`Cannot convert argument of type ${b.ea.la ? b.ea.la.name : b.ea.ha.name} to parameter type ${this.name}`); c = Nb(b.ea.ga, b.ea.ha.fa, this.fa); if (this.Ba) switch (void 0 === b.ea.ka && P("Passing raw pointer to smart pointer is illegal"),
          this.pb) { case 0: b.ea.la === this ? c = b.ea.ka : P(`Cannot convert argument of type ${b.ea.la ? b.ea.la.name : b.ea.ha.name} to parameter type ${this.name}`); break; case 1: c = b.ea.ka; break; case 2: if (b.ea.la === this) c = b.ea.ka; else { var d = b.clone(); c = this.jb(c, kb(function () { d["delete"]() })); null !== a && a.push(this.pa, c) } break; default: P("Unsupporting sharing policy") }return c
      }
      function Rb(a, b) { if (null === b) return this.Ca && P(`null is not a valid ${this.name}`), 0; b.ea || P(`Cannot pass "${Pb(b)}" as a ${this.name}`); b.ea.ga || P(`Cannot pass deleted object as a pointer of type ${this.name}`); b.ea.ha.Aa && P(`Cannot convert argument of type ${b.ea.ha.name} to parameter type ${this.name}`); return Nb(b.ea.ga, b.ea.ha.fa, this.fa) }
      function Y(a, b, c, d) { this.name = a; this.fa = b; this.Ca = c; this.Aa = d; this.Ba = !1; this.pa = this.jb = this.Da = this.Ja = this.pb = this.ib = void 0; void 0 !== b.ia ? this.toWireType = Qb : (this.toWireType = d ? Ob : Rb, this.ma = null) } function Sb(a, b) { A.hasOwnProperty(a) || Bb("Replacing nonexistant public symbol"); A[a] = b; A[a].va = void 0 }
      function Tb(a, b) { var c = []; return function () { c.length = 0; Object.assign(c, arguments); if (a.includes("j")) { var d = A["dynCall_" + a]; d = c && c.length ? d.apply(null, [b].concat(c)) : d.call(null, b) } else d = Da.get(b).apply(null, c); return d } } function Z(a, b) { a = Q(a); var c = a.includes("j") ? Tb(a, b) : Da.get(b); "function" != typeof c && P(`unknown function pointer with signature ${a}: ${b}`); return c } var Ub = void 0;
      function Vb(a, b) { function c(e) { f[e] || S[e] || (Hb[e] ? Hb[e].forEach(c) : (d.push(e), f[e] = !0)) } var d = [], f = {}; b.forEach(c); throw new Ub(`${a}: ` + d.map(rb).join([", "])); }
      function Wb(a, b, c, d, f) {
        var e = b.length; 2 > e && P("argTypes array size mismatch! Must at least get return value and 'this' types!"); var k = null !== b[1] && null !== c, h = !1; for (c = 1; c < b.length; ++c)if (null !== b[c] && void 0 === b[c].ma) { h = !0; break } var l = "void" !== b[0].name, m = e - 2, n = Array(m), p = [], t = []; return function () {
          arguments.length !== m && P(`function ${a} called with ${arguments.length} arguments, expected ${m} args!`); t.length = 0; p.length = k ? 2 : 1; p[0] = f; if (k) { var v = b[1].toWireType(t, this); p[1] = v } for (var u = 0; u < m; ++u)n[u] =
            b[u + 2].toWireType(t, arguments[u]), p.push(n[u]); u = d.apply(null, p); if (h) Eb(t); else for (var B = k ? 1 : 2; B < b.length; B++) { var H = 1 === B ? v : n[B - 2]; null !== b[B].ma && b[B].ma(H) } v = l ? b[0].fromWireType(u) : void 0; return v
        }
      } function Xb(a, b) { for (var c = [], d = 0; d < a; d++)c.push(y()[b + 4 * d >> 2]); return c } function Yb(a) { a >= N.Ha && 0 === --N.get(a).Ka && N.ab(a) } function Pb(a) { if (null === a) return "null"; var b = typeof a; return "object" === b || "array" === b || "function" === b ? a.toString() : "" + a }
      function Zb(a, b) { switch (b) { case 2: return function (c) { var d = this.fromWireType; g.buffer != q.buffer && r(); return d.call(this, Ba[c >> 2]) }; case 3: return function (c) { return this.fromWireType(ja()[c >> 3]) }; default: throw new TypeError("Unknown float type: " + a); } }
      function $b(a, b, c) { switch (b) { case 0: return c ? function (d) { return aa()[d] } : function (d) { return w()[d] }; case 1: return c ? function (d) { return ca()[d >> 1] } : function (d) { return ea()[d >> 1] }; case 2: return c ? function (d) { return x()[d >> 2] } : function (d) { return y()[d >> 2] }; default: throw new TypeError("Unknown integer type: " + a); } } function ac(a, b) { for (var c = "", d = 0; !(d >= b / 2); ++d) { var f = ca()[a + 2 * d >> 1]; if (0 == f) break; c += String.fromCharCode(f) } return c }
      function bc(a, b, c) { void 0 === c && (c = 2147483647); if (2 > c) return 0; c -= 2; var d = b; c = c < 2 * a.length ? c / 2 : a.length; for (var f = 0; f < c; ++f) { var e = a.charCodeAt(f); ca()[b >> 1] = e; b += 2 } ca()[b >> 1] = 0; return b - d } function cc(a) { return 2 * a.length } function dc(a, b) { for (var c = 0, d = ""; !(c >= b / 4);) { var f = x()[a + 4 * c >> 2]; if (0 == f) break; ++c; 65536 <= f ? (f -= 65536, d += String.fromCharCode(55296 | f >> 10, 56320 | f & 1023)) : d += String.fromCharCode(f) } return d }
      function ec(a, b, c) { void 0 === c && (c = 2147483647); if (4 > c) return 0; var d = b; c = d + c - 4; for (var f = 0; f < a.length; ++f) { var e = a.charCodeAt(f); if (55296 <= e && 57343 >= e) { var k = a.charCodeAt(++f); e = 65536 + ((e & 1023) << 10) | k & 1023 } x()[b >> 2] = e; b += 4; if (b + 4 > c) break } x()[b >> 2] = 0; return b - d } function hc(a) { for (var b = 0, c = 0; c < a.length; ++c) { var d = a.charCodeAt(c); 55296 <= d && 57343 >= d && ++c; b += 4 } return b } function ic(a) { if (!Aa) try { if (a(), !Ia()) try { E ? fb(J) : Xa(J) } catch (b) { Za(b) } } catch (b) { Za(b) } }
      function jc(a) { "function" === typeof Atomics.rb && (Atomics.rb(x(), a >> 2, a).value.then(bb), a += 128, Atomics.store(x(), a >> 2, 1)) } A.__emscripten_thread_mailbox_await = jc; function bb() { var a = ab(); a && (jc(a), ic(() => kc())) } A.checkMailbox = bb; var lc = {}; function mc(a) { var b = lc[a]; return void 0 === b ? Q(a) : b } var nc = []; function oc(a) { var b = nc.length; nc.push(a); return b } function pc(a, b) { for (var c = Array(a), d = 0; d < a; ++d)c[d] = tb(y()[b + 4 * d >> 2], "parameter " + d); return c } var qc = [], rc;
      rc = D ? () => { var a = process.hrtime(); return 1E3 * a[0] + a[1] / 1E6 } : () => performance.timeOrigin + performance.now(); function sc(a) { var b = tc(); a = a(); eb(b); return a } function Wa(a, b) { var c = arguments.length - 2, d = arguments; return sc(() => { for (var f = uc(8 * c), e = f >> 3, k = 0; k < c; k++) { var h = d[2 + k]; ja()[e + k] = h } return vc(a, c, f, b) }) } var wc = []; function xc(a) { return E ? Wa(3, 1, a) : 52 } function yc(a, b, c, d, f) { return E ? Wa(4, 1, a, b, c, d, f) : 70 } var zc = [null, [], []];
      function Ac(a, b, c, d) { if (E) return Wa(5, 1, a, b, c, d); for (var f = 0, e = 0; e < c; e++) { var k = y()[b >> 2], h = y()[b + 4 >> 2]; b += 8; for (var l = 0; l < h; l++) { var m = w()[k + l], n = zc[a]; 0 === m || 10 === m ? ((1 === a ? xa : G)(Ua(n, 0)), n.length = 0) : n.push(m) } f += h } y()[d >> 2] = f; return 0 } M.cb(); O = A.BindingError = ib("BindingError"); N.oa.push({ value: void 0 }, { value: null }, { value: !0 }, { value: !1 }); N.Ha = N.oa.length; A.count_emval_handles = function () { for (var a = 0, b = N.Ha; b < N.oa.length; ++b)void 0 !== N.oa[b] && ++a; return a }; lb = A.PureVirtualError = ib("PureVirtualError");
      for (var Bc = Array(256), Cc = 0; 256 > Cc; ++Cc)Bc[Cc] = String.fromCharCode(Cc); mb = Bc; A.getInheritedInstanceCount = function () { return Object.keys(R).length }; A.getLiveInheritedInstances = function () { var a = [], b; for (b in R) R.hasOwnProperty(b) && a.push(R[b]); return a }; A.flushPendingDeletes = ob; A.setDelayFunction = function (a) { pb = a; nb.length && pb && pb(ob) }; Ab = A.InternalError = ib("InternalError");
      X.prototype.isAliasOf = function (a) { if (!(this instanceof X && a instanceof X)) return !1; var b = this.ea.ha.fa, c = this.ea.ga, d = a.ea.ha.fa; for (a = a.ea.ga; b.ia;)c = b.ya(c), b = b.ia; for (; d.ia;)a = d.ya(a), d = d.ia; return b === d && c === a };
      X.prototype.clone = function () { this.ea.ga || Jb(this); if (this.ea.xa) return this.ea.count.value += 1, this; var a = U, b = Object, c = b.create, d = Object.getPrototypeOf(this), f = this.ea; a = a(c.call(b, d, { ea: { value: { count: f.count, wa: f.wa, xa: f.xa, ga: f.ga, ha: f.ha, ka: f.ka, la: f.la } } })); a.ea.count.value += 1; a.ea.wa = !1; return a }; X.prototype["delete"] = function () { this.ea.ga || Jb(this); this.ea.wa && !this.ea.xa && P("Object already scheduled for deletion"); ub(this); wb(this.ea); this.ea.xa || (this.ea.ka = void 0, this.ea.ga = void 0) };
      X.prototype.isDeleted = function () { return !this.ea.ga }; X.prototype.deleteLater = function () { this.ea.ga || Jb(this); this.ea.wa && !this.ea.xa && P("Object already scheduled for deletion"); nb.push(this); 1 === nb.length && pb && pb(ob); this.ea.wa = !0; return this }; Y.prototype.Wa = function (a) { this.Ja && (a = this.Ja(a)); return a }; Y.prototype.Ea = function (a) { this.pa && this.pa(a) }; Y.prototype.argPackAdvance = 8; Y.prototype.readValueFromPointer = Fb; Y.prototype.deleteObject = function (a) { if (null !== a) a["delete"]() };
      Y.prototype.fromWireType = function (a) {
        function b() { return this.Ba ? Cb(this.fa.qa, { ha: this.ib, ga: c, la: this, ka: a }) : Cb(this.fa.qa, { ha: this, ga: a }) } var c = this.Wa(a); if (!c) return this.Ea(a), null; var d = zb(this.fa, c); if (void 0 !== d) { if (0 === d.ea.count.value) return d.ea.ga = c, d.ea.ka = a, d.clone(); d = d.clone(); this.Ea(a); return d } d = this.fa.Ua(c); d = yb[d]; if (!d) return b.call(this); d = this.Aa ? d.Pa : d.pointerType; var f = xb(c, this.fa, d.fa); return null === f ? b.call(this) : this.Ba ? Cb(d.fa.qa, { ha: d, ga: f, la: this, ka: a }) : Cb(d.fa.qa,
          { ha: d, ga: f })
      }; Ub = A.UnboundTypeError = ib("UnboundTypeError");
      var Dc = [null, Va, Ya, xc, yc, Ac], Gc = {
        E: function (a) { Ec(a, !C, 1, !qa, 65536); M.Ma() }, y: function (a) { E ? postMessage({ cmd: "cleanupThread", thread: a }) : Ta(a) }, r: function (a, b, c) {
          a = Q(a); b = tb(b, "wrapper"); c = jb(c); var d = [].slice, f = b.fa, e = f.qa, k = f.ia.qa, h = f.ia.constructor; a = hb(a, function () { f.ia.Ia.forEach(function (m) { if (this[m] === k[m]) throw new lb(`Pure virtual function ${m} must be implemented in JavaScript`); }.bind(this)); Object.defineProperty(this, "__parent", { value: e }); this.__construct.apply(this, d.call(arguments)) });
          e.__construct = function () { this === e && P("Pass correct 'this' to __construct"); var m = h.implement.apply(void 0, [this].concat(d.call(arguments))); ub(m); var n = m.ea; m.notifyOnDestruction(); n.xa = !0; Object.defineProperties(this, { ea: { value: n } }); U(this); m = n.ga; m = qb(f, m); R.hasOwnProperty(m) ? P(`Tried to register registered instance: ${m}`) : R[m] = this }; e.__destruct = function () { this === e && P("Pass correct 'this' to __destruct"); ub(this); var m = this.ea.ga; m = qb(f, m); R.hasOwnProperty(m) ? delete R[m] : P(`Tried to unregister unregistered instance: ${m}`) };
          a.prototype = Object.create(e); for (var l in c) a.prototype[l] = c[l]; return kb(a)
        }, l: function (a) {
          var b = Db[a]; delete Db[a]; var c = b.Da, d = b.pa, f = b.Ga, e = f.map(k => k.Za).concat(f.map(k => k.nb)); V([a], e, k => {
            var h = {}; f.forEach((l, m) => { var n = k[m], p = l.Xa, t = l.Ya, v = k[m + f.length], u = l.mb, B = l.ob; h[l.Ta] = { read: H => n.fromWireType(p(t, H)), write: (H, ka) => { var z = []; u(B, H, v.toWireType(z, ka)); Eb(z) } } }); return [{
              name: b.name, fromWireType: function (l) { var m = {}, n; for (n in h) m[n] = h[n].read(l); d(l); return m }, toWireType: function (l, m) {
                for (var n in h) if (!(n in
                  m)) throw new TypeError(`Missing field: "${n}"`); var p = c(); for (n in h) h[n].write(p, m[n]); null !== l && l.push(d, p); return p
              }, argPackAdvance: 8, readValueFromPointer: Fb, ma: d
            }]
          })
        }, x: function () { }, L: function (a, b, c, d, f) {
          var e = Ib(c); b = Q(b); W(a, {
            name: b, fromWireType: function (k) { return !!k }, toWireType: function (k, h) { return h ? d : f }, argPackAdvance: 8, readValueFromPointer: function (k) {
              if (1 === c) var h = aa(); else if (2 === c) h = ca(); else if (4 === c) h = x(); else throw new TypeError("Unknown boolean type size: " + b); return this.fromWireType(h[k >>
                e])
            }, ma: null
          })
        }, h: function (a, b, c, d, f, e, k, h, l, m, n, p, t) {
          n = Q(n); e = Z(f, e); h && (h = Z(k, h)); m && (m = Z(l, m)); t = Z(p, t); var v = gb(n); Lb(v, function () { Vb(`Cannot construct ${n} due to unbound types`, [d]) }); V([a, b, c], d ? [d] : [], function (u) {
            u = u[0]; if (d) { var B = u.fa; var H = B.qa } else H = X.prototype; u = hb(v, function () {
              if (Object.getPrototypeOf(this) !== ka) throw new O("Use 'new' to construct " + n); if (void 0 === z.sa) throw new O(n + " has no accessible constructor"); var fc = z.sa[arguments.length]; if (void 0 === fc) throw new O(`Tried to invoke ctor of ${n} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(z.sa).toString()}) parameters instead!`);
              return fc.apply(this, arguments)
            }); var ka = Object.create(H, { constructor: { value: u } }); u.prototype = ka; var z = new Mb(n, u, ka, t, B, e, h, m); z.ia && (void 0 === z.ia.za && (z.ia.za = []), z.ia.za.push(z)); B = new Y(n, z, !0, !1); H = new Y(n + "*", z, !1, !1); var gc = new Y(n + " const*", z, !1, !0); yb[a] = { pointerType: H, Pa: gc }; Sb(v, u); return [B, H, gc]
          })
        }, d: function (a, b, c, d, f, e, k) {
          var h = Xb(c, d); b = Q(b); e = Z(f, e); V([], [a], function (l) {
            function m() { Vb(`Cannot call ${n} due to unbound types`, h) } l = l[0]; var n = `${l.name}.${b}`; b.startsWith("@@") && (b =
              Symbol[b.substring(2)]); var p = l.fa.constructor; void 0 === p[b] ? (m.va = c - 1, p[b] = m) : (Kb(p, b, n), p[b].ja[c - 1] = m); V([], h, function (t) { t = [t[0], null].concat(t.slice(1)); t = Wb(n, t, null, e, k); void 0 === p[b].ja ? (t.va = c - 1, p[b] = t) : p[b].ja[c - 1] = t; if (l.fa.za) for (const v of l.fa.za) v.constructor.hasOwnProperty(b) || (v.constructor[b] = t); return [] }); return []
          })
        }, q: function (a, b, c, d, f, e) {
          0 < b || I(); var k = Xb(b, c); f = Z(d, f); V([], [a], function (h) {
            h = h[0]; var l = `constructor ${h.name}`; void 0 === h.fa.sa && (h.fa.sa = []); if (void 0 !== h.fa.sa[b -
              1]) throw new O(`Cannot register multiple constructors with identical number of parameters (${b - 1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`); h.fa.sa[b - 1] = () => { Vb(`Cannot construct ${h.name} due to unbound types`, k) }; V([], k, function (m) { m.splice(1, 0, null); h.fa.sa[b - 1] = Wb(l, m, null, f, e); return [] }); return []
          })
        }, b: function (a, b, c, d, f, e, k, h) {
          var l = Xb(c, d); b = Q(b); e = Z(f, e); V([], [a], function (m) {
            function n() {
              Vb(`Cannot call ${p} due to unbound types`,
                l)
            } m = m[0]; var p = `${m.name}.${b}`; b.startsWith("@@") && (b = Symbol[b.substring(2)]); h && m.fa.Ia.push(b); var t = m.fa.qa, v = t[b]; void 0 === v || void 0 === v.ja && v.className !== m.name && v.va === c - 2 ? (n.va = c - 2, n.className = m.name, t[b] = n) : (Kb(t, b, p), t[b].ja[c - 2] = n); V([], l, function (u) { u = Wb(p, u, m, e, k); void 0 === t[b].ja ? (u.va = c - 2, t[b] = u) : t[b].ja[c - 2] = u; return [] }); return []
          })
        }, K: function (a, b) {
          b = Q(b); W(a, {
            name: b, fromWireType: function (c) { var d = jb(c); Yb(c); return d }, toWireType: function (c, d) { return kb(d) }, argPackAdvance: 8, readValueFromPointer: Fb,
            ma: null
          })
        }, o: function (a, b, c) { c = Ib(c); b = Q(b); W(a, { name: b, fromWireType: function (d) { return d }, toWireType: function (d, f) { return f }, argPackAdvance: 8, readValueFromPointer: Zb(b, c), ma: null }) }, e: function (a, b, c, d, f) { b = Q(b); -1 === f && (f = 4294967295); f = Ib(c); var e = h => h; if (0 === d) { var k = 32 - 8 * c; e = h => h << k >>> k } c = b.includes("unsigned") ? function (h, l) { return l >>> 0 } : function (h, l) { return l }; W(a, { name: b, fromWireType: e, toWireType: c, argPackAdvance: 8, readValueFromPointer: $b(b, f, 0 !== d), ma: null }) }, c: function (a, b, c) {
          function d(e) {
            e >>=
            2; var k = y(); return new f(k.buffer, k[e + 1], k[e])
          } var f = [Int8Array, Uint8Array, Int16Array, Uint16Array, Int32Array, Uint32Array, Float32Array, Float64Array][b]; c = Q(c); W(a, { name: c, fromWireType: d, argPackAdvance: 8, readValueFromPointer: d }, { bb: !0 })
        }, p: function (a, b) {
          b = Q(b); var c = "std::string" === b; W(a, {
            name: b, fromWireType: function (d) {
              var f = y()[d >> 2], e = d + 4; if (c) for (var k = e, h = 0; h <= f; ++h) { var l = e + h; if (h == f || 0 == w()[l]) { var m = k; k = l - k; m = m ? Ua(w(), m, k) : ""; if (void 0 === n) var n = m; else n += String.fromCharCode(0), n += m; k = l + 1 } } else {
                n =
                Array(f); for (h = 0; h < f; ++h)n[h] = String.fromCharCode(w()[e + h]); n = n.join("")
              } T(d); return n
            }, toWireType: function (d, f) {
              f instanceof ArrayBuffer && (f = new Uint8Array(f)); var e = "string" == typeof f; e || f instanceof Uint8Array || f instanceof Uint8ClampedArray || f instanceof Int8Array || P("Cannot pass non-string to std::string"); var k; if (c && e) for (var h = k = 0; h < f.length; ++h) { var l = f.charCodeAt(h); 127 >= l ? k++ : 2047 >= l ? k += 2 : 55296 <= l && 57343 >= l ? (k += 4, ++h) : k += 3 } else k = f.length; l = k; k = Fc(4 + l + 1); h = k + 4; y()[k >> 2] = l; if (c && e) {
                if (l +=
                  1, e = w(), 0 < l) { l = h + l - 1; for (var m = 0; m < f.length; ++m) { var n = f.charCodeAt(m); if (55296 <= n && 57343 >= n) { var p = f.charCodeAt(++m); n = 65536 + ((n & 1023) << 10) | p & 1023 } if (127 >= n) { if (h >= l) break; e[h++] = n } else { if (2047 >= n) { if (h + 1 >= l) break; e[h++] = 192 | n >> 6 } else { if (65535 >= n) { if (h + 2 >= l) break; e[h++] = 224 | n >> 12 } else { if (h + 3 >= l) break; e[h++] = 240 | n >> 18; e[h++] = 128 | n >> 12 & 63 } e[h++] = 128 | n >> 6 & 63 } e[h++] = 128 | n & 63 } } e[h] = 0 }
              } else if (e) for (e = 0; e < l; ++e)m = f.charCodeAt(e), 255 < m && (T(h), P("String has UTF-16 code units that do not fit in 8 bits")),
                w()[h + e] = m; else for (e = 0; e < l; ++e)w()[h + e] = f[e]; null !== d && d.push(T, k); return k
            }, argPackAdvance: 8, readValueFromPointer: Fb, ma: function (d) { T(d) }
          })
        }, k: function (a, b, c) {
          c = Q(c); if (2 === b) { var d = ac; var f = bc; var e = cc; var k = () => ea(); var h = 1 } else 4 === b && (d = dc, f = ec, e = hc, k = () => y(), h = 2); W(a, {
            name: c, fromWireType: function (l) { for (var m = y()[l >> 2], n = k(), p, t = l + 4, v = 0; v <= m; ++v) { var u = l + 4 + v * b; if (v == m || 0 == n[u >> h]) t = d(t, u - t), void 0 === p ? p = t : (p += String.fromCharCode(0), p += t), t = u + b } T(l); return p }, toWireType: function (l, m) {
              "string" !=
              typeof m && P(`Cannot pass non-string to C++ string type ${c}`); var n = e(m), p = Fc(4 + n + b); y()[p >> 2] = n >> h; f(m, p + 4, n + b); null !== l && l.push(T, p); return p
            }, argPackAdvance: 8, readValueFromPointer: Fb, ma: function (l) { T(l) }
          })
        }, m: function (a, b, c, d, f, e) { Db[a] = { name: Q(b), Da: Z(c, d), pa: Z(f, e), Ga: [] } }, j: function (a, b, c, d, f, e, k, h, l, m) { Db[a].Ga.push({ Ta: Q(b), Za: c, Xa: Z(d, f), Ya: e, nb: k, mb: Z(h, l), ob: m }) }, M: function (a, b) { b = Q(b); W(a, { fb: !0, name: b, argPackAdvance: 0, fromWireType: function () { }, toWireType: function () { } }) }, F: function (a,
          b) { a == b ? setTimeout(() => bb()) : E ? postMessage({ targetThread: a, cmd: "checkMailbox" }) : (a = M.na[a]) && a.postMessage({ cmd: "checkMailbox" }) }, C: function () { return -1 }, D: jc, H: function (a) { D && M.na[a].ref() }, u: function (a, b, c, d, f) { a = nc[a]; b = jb(b); c = mc(c); var e = []; y()[d >> 2] = kb(e); return a(b, c, e, f) }, v: function (a, b, c, d) { a = nc[a]; b = jb(b); c = mc(c); a(b, c, null, d) }, i: Yb, n: function (a, b) {
            var c = pc(a, b), d = c[0]; b = d.name + "_$" + c.slice(1).map(function (k) { return k.name }).join("_") + "$"; var f = qc[b]; if (void 0 !== f) return f; var e = Array(a -
              1); f = oc((k, h, l, m) => { for (var n = 0, p = 0; p < a - 1; ++p)e[p] = c[p + 1].readValueFromPointer(m + n), n += c[p + 1].argPackAdvance; k = k[h].apply(k, e); for (p = 0; p < a - 1; ++p)c[p + 1].Ra && c[p + 1].Ra(e[p]); if (!d.fb) return d.toWireType(l, k) }); return qc[b] = f
          }, s: function (a) { 4 < a && (N.get(a).Ka += 1) }, t: function (a) { var b = jb(a); Eb(b); Yb(a) }, f: function () { I("") }, G: function () { Ha += 1; throw "unwind"; }, g: rc, B: function (a, b, c) { wc.length = b; c >>= 3; for (var d = 0; d < b; d++)wc[d] = ja()[c + d]; return Dc[a].apply(null, wc) }, A: function (a) {
            var b = w().length; a >>>= 0; if (a <=
              b || 2147483648 < a) return !1; for (var c = 1; 4 >= c; c *= 2) { var d = b * (1 + .2 / c); d = Math.min(d, a + 100663296); var f = Math, e = f.min; d = Math.max(a, d); d += (65536 - d % 65536) % 65536; a: { var k = g.buffer; try { g.grow(e.call(f, 2147483648, d) - k.byteLength + 65535 >>> 16); r(); var h = 1; break a } catch (l) { } h = void 0 } if (h) return !0 } return !1
          }, z: Xa, J: xc, w: yc, I: Ac, a: g || A.wasmMemory
      };
      (function () {
        function a(c, d) { c = c.exports; A.asm = c; M.Na.push(A.asm.O); Da = A.asm._; Fa.unshift(A.asm.N); za = d; M.gb(() => { K--; A.monitorRunDependencies && A.monitorRunDependencies(K); if (0 == K && (null !== Ka && (clearInterval(Ka), Ka = null), La)) { var f = La; La = null; f() } }); return c } var b = { a: Gc }; K++; A.monitorRunDependencies && A.monitorRunDependencies(K); if (A.instantiateWasm) try { return A.instantiateWasm(b, a) } catch (c) { G("Module.instantiateWasm callback failed with error: " + c), na(c) } Qa(b, function (c) { a(c.instance, c.module) }).catch(na);
        return {}
      })(); A.__emscripten_tls_init = function () { return (A.__emscripten_tls_init = A.asm.O).apply(null, arguments) }; var ab = A._pthread_self = function () { return (ab = A._pthread_self = A.asm.P).apply(null, arguments) }; function sb() { return (sb = A.asm.Q).apply(null, arguments) } A.__embind_initialize_bindings = function () { return (A.__embind_initialize_bindings = A.asm.R).apply(null, arguments) }; var Ec = A.__emscripten_thread_init = function () { return (Ec = A.__emscripten_thread_init = A.asm.S).apply(null, arguments) };
      A.__emscripten_thread_crashed = function () { return (A.__emscripten_thread_crashed = A.asm.T).apply(null, arguments) }; function vc() { return (vc = A.asm.U).apply(null, arguments) } function $a() { return ($a = A.asm.V).apply(null, arguments) } var fb = A.__emscripten_thread_exit = function () { return (fb = A.__emscripten_thread_exit = A.asm.W).apply(null, arguments) }; function Fc() { return (Fc = A.asm.X).apply(null, arguments) } var kc = A.__emscripten_check_mailbox = function () { return (kc = A.__emscripten_check_mailbox = A.asm.Y).apply(null, arguments) };
      function T() { return (T = A.asm.Z).apply(null, arguments) } function db() { return (db = A.asm.$).apply(null, arguments) } function tc() { return (tc = A.asm.aa).apply(null, arguments) } function eb() { return (eb = A.asm.ba).apply(null, arguments) } function uc() { return (uc = A.asm.ca).apply(null, arguments) } A.dynCall_jiji = function () { return (A.dynCall_jiji = A.asm.da).apply(null, arguments) }; A.keepRuntimeAlive = Ia; A.wasmMemory = g; A.ExitStatus = Ra; A.PThread = M; var Hc; La = function Ic() { Hc || Jc(); Hc || (La = Ic) };
      function Jc() {
        function a() { if (!Hc && (Hc = !0, A.calledRun = !0, !Aa)) { E || cb(Fa); ma(A); if (A.onRuntimeInitialized) A.onRuntimeInitialized(); if (!E) { if (A.postRun) for ("function" == typeof A.postRun && (A.postRun = [A.postRun]); A.postRun.length;) { var b = A.postRun.shift(); Ga.unshift(b) } cb(Ga) } } } if (!(0 < K)) if (E) ma(A), E || cb(Fa), startWorker(A); else {
          if (A.preRun) for ("function" == typeof A.preRun && (A.preRun = [A.preRun]); A.preRun.length;)Ja(); cb(Ea); 0 < K || (A.setStatus ? (A.setStatus("Running..."), setTimeout(function () {
            setTimeout(function () { A.setStatus("") },
              1); a()
          }, 1)) : a())
        }
      } if (A.preInit) for ("function" == typeof A.preInit && (A.preInit = [A.preInit]); 0 < A.preInit.length;)A.preInit.pop()(); Jc();


      return loadYoga.ready
    }

  );
})();
// if (typeof exports === 'object' && typeof module === 'object')
//   module.exports = loadYoga;
// else if (typeof define === 'function' && define['amd'])
//   define([], function() { return loadYoga; });
// else if (typeof exports === 'object')
//   exports["loadYoga"] = loadYoga;
export default loadYoga